/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as DocsOverviewImport } from "./routes/docs/overview";
import { Route as DocsInstallationImport } from "./routes/docs/installation";

// Create/Update Routes

const DocsOverviewRoute = DocsOverviewImport.update({
  id: "/docs/overview",
  path: "/docs/overview",
  getParentRoute: () => rootRoute,
} as any);

const DocsInstallationRoute = DocsInstallationImport.update({
  id: "/docs/installation",
  path: "/docs/installation",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/docs/installation": {
      id: "/docs/installation";
      path: "/docs/installation";
      fullPath: "/docs/installation";
      preLoaderRoute: typeof DocsInstallationImport;
      parentRoute: typeof rootRoute;
    };
    "/docs/overview": {
      id: "/docs/overview";
      path: "/docs/overview";
      fullPath: "/docs/overview";
      preLoaderRoute: typeof DocsOverviewImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/docs/installation": typeof DocsInstallationRoute;
  "/docs/overview": typeof DocsOverviewRoute;
}

export interface FileRoutesByTo {
  "/docs/installation": typeof DocsInstallationRoute;
  "/docs/overview": typeof DocsOverviewRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/docs/installation": typeof DocsInstallationRoute;
  "/docs/overview": typeof DocsOverviewRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/docs/installation" | "/docs/overview";
  fileRoutesByTo: FileRoutesByTo;
  to: "/docs/installation" | "/docs/overview";
  id: "__root__" | "/docs/installation" | "/docs/overview";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  DocsInstallationRoute: typeof DocsInstallationRoute;
  DocsOverviewRoute: typeof DocsOverviewRoute;
}

const rootRouteChildren: RootRouteChildren = {
  DocsInstallationRoute: DocsInstallationRoute,
  DocsOverviewRoute: DocsOverviewRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/docs/installation",
        "/docs/overview"
      ]
    },
    "/docs/installation": {
      "filePath": "docs/installation.tsx"
    },
    "/docs/overview": {
      "filePath": "docs/overview.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
